<?php

namespace Database\Seeders;

use App\Models\DietTracker\ExerciseDatabase;
use Illuminate\Database\Seeder;

class ExerciseGuideSeeder extends Seeder
{
    public function run(): void
    {
        $guides = [
            'Jalan Kaki' => [
                'instruksi' => "1. Berdiri tegak, pandangan ke depan\n2. Ayunkan lengan secara alami\n3. Langkah kaki dengan tumit mendarat duluan\n4. Jaga postur tubuh tetap tegak\n5. Bernapas secara teratur\n6. Mulai dengan 15 menit, tingkatkan bertahap",
                'manfaat' => 'Meningkatkan kesehatan jantung, membakar kalori tanpa tekanan sendi, menurunkan stres, memperbaiki mood, cocok untuk semua usia.',
                'otot_target' => 'Kaki, betis, paha',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-60 menit',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Jalan Cepat' => [
                'instruksi' => "1. Jaga postur tegak, dagu sejajar tanah\n2. Tekuk siku 90 derajat, ayunkan lengan aktif\n3. Langkah lebih panjang dari jalan biasa\n4. Kecepatan 5-7 km/jam\n5. Tumit mendarat duluan, dorong dengan jari kaki\n6. Jaga napas teratur, bisa bicara tapi sedikit terengah",
                'manfaat' => 'Membakar 2x lebih banyak kalori dari jalan biasa, meningkatkan stamina kardiovaskular, memperkuat tulang.',
                'otot_target' => 'Kaki, betis, paha, glutes',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-45 menit',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Jogging' => [
                'instruksi' => "1. Pemanasan 5 menit jalan cepat\n2. Mulai berlari pelan, kecepatan 6-8 km/jam\n3. Mendarat dengan bagian tengah kaki (midfoot)\n4. Jaga langkah pendek dan cepat\n5. Lengan ditekuk 90 derajat, ayun ke depan-belakang\n6. Bernapas: hirup lewat hidung, buang lewat mulut\n7. Pendinginan 5 menit jalan pelan",
                'manfaat' => 'Membakar lemak efektif, meningkatkan daya tahan jantung-paru, memperkuat tulang dan sendi, melepas endorfin (hormon bahagia).',
                'otot_target' => 'Kaki, paha, betis, core',
                'durasi_rekomendasi' => 30,
                'set_rep' => '20-40 menit',
                'level' => 'pemula',
                'peralatan' => 'sepatu_lari',
            ],
            'Lari' => [
                'instruksi' => "1. Pemanasan 10 menit jogging pelan\n2. Tingkatkan kecepatan ke 9-12 km/jam\n3. Condongkan badan sedikit ke depan\n4. Langkah cepat dan ringan\n5. Ayunkan lengan kuat ke depan-belakang\n6. Bernapas dalam dan teratur\n7. Interval: lari 3 menit, jogging 1 menit\n8. Pendinginan 5-10 menit",
                'manfaat' => 'Membakar kalori sangat tinggi (12 kal/menit), meningkatkan VO2max, memperkuat jantung, meningkatkan metabolisme basal.',
                'otot_target' => 'Kaki, paha, betis, core, glutes',
                'durasi_rekomendasi' => 25,
                'set_rep' => '20-30 menit',
                'level' => 'menengah',
                'peralatan' => 'sepatu_lari',
            ],
            'Bersepeda' => [
                'instruksi' => "1. Atur tinggi sadel: kaki hampir lurus saat pedal di bawah\n2. Pegang stang dengan rileks, siku sedikit ditekuk\n3. Kayuh dengan kecepatan stabil 60-80 RPM\n4. Gunakan gigi rendah saat menanjak\n5. Jaga punggung lurus, jangan membungkuk\n6. Bernapas teratur",
                'manfaat' => 'Low-impact cardio (ramah sendi), memperkuat paha dan betis, meningkatkan stamina, cocok untuk yang punya masalah lutut.',
                'otot_target' => 'Paha, betis, glutes, core',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-60 menit',
                'level' => 'pemula',
                'peralatan' => 'sepeda',
            ],
            'Bersepeda Cepat' => [
                'instruksi' => "1. Pemanasan 5 menit kayuh pelan\n2. Tingkatkan kecepatan dan resistensi\n3. Interval: 2 menit cepat, 1 menit pelan\n4. Berdiri saat menanjak untuk power ekstra\n5. Jaga RPM 80-100 saat sprint\n6. Pendinginan 5 menit kayuh pelan",
                'manfaat' => 'Membakar kalori tinggi, meningkatkan kekuatan kaki, melatih daya tahan anaerobik, mempercepat metabolisme.',
                'otot_target' => 'Paha, betis, glutes, hamstring',
                'durasi_rekomendasi' => 25,
                'set_rep' => '20-30 menit',
                'level' => 'menengah',
                'peralatan' => 'sepeda',
            ],
            'Renang' => [
                'instruksi' => "1. Pemanasan: berenang pelan 2-3 lap\n2. Gaya bebas: kepala masuk air saat lengan mendorong\n3. Tendangan kaki dari pinggul, bukan lutut\n4. Bernapas ke samping setiap 3 stroke\n5. Variasi gaya: bebas, dada, punggung\n6. Interval: 1 lap cepat, 1 lap pelan\n7. Pendinginan: 2 lap pelan",
                'manfaat' => 'Full-body workout, zero-impact (sangat ramah sendi), melatih pernapasan, membakar kalori tinggi, memperbaiki postur.',
                'otot_target' => 'Seluruh tubuh: lengan, punggung, core, kaki',
                'durasi_rekomendasi' => 30,
                'set_rep' => '20-40 menit',
                'level' => 'pemula',
                'peralatan' => 'kolam_renang',
            ],
            'Lompat Tali' => [
                'instruksi' => "1. Pegang tali di samping pinggul, siku ditekuk\n2. Putar tali dengan pergelangan tangan (bukan lengan)\n3. Lompat rendah, cukup 2-3 cm dari lantai\n4. Mendarat dengan ujung kaki, lutut sedikit ditekuk\n5. Jaga core tetap kencang\n6. Mulai: 30 detik lompat, 30 detik istirahat\n7. Tingkatkan bertahap ke 1-2 menit tanpa henti",
                'manfaat' => 'Membakar kalori sangat tinggi (10-12 kal/menit), meningkatkan koordinasi, memperkuat tulang kaki, melatih kelincahan.',
                'otot_target' => 'Betis, paha, bahu, lengan, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '10-20 menit (interval)',
                'level' => 'menengah',
                'peralatan' => 'tali_skipping',
            ],
            'Senam Aerobik' => [
                'instruksi' => "1. Pemanasan 5 menit: marching in place, arm circles\n2. Step touch ke kanan-kiri dengan ayunan lengan\n3. Grapevine: langkah silang ke samping\n4. Knee lift: angkat lutut bergantian\n5. Jumping jack: lompat buka-tutup kaki + lengan\n6. V-step: langkah maju membentuk huruf V\n7. Pendinginan: stretching 5 menit",
                'manfaat' => 'Meningkatkan kebugaran kardiovaskular, membakar lemak, meningkatkan koordinasi, menyenangkan dan bisa dilakukan bersama.',
                'otot_target' => 'Seluruh tubuh',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-45 menit',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Naik Tangga' => [
                'instruksi' => "1. Mulai dengan kecepatan normal, naik 1 anak tangga\n2. Jaga postur tegak, jangan membungkuk\n3. Dorong dengan tumit saat naik\n4. Gunakan pegangan tangan jika perlu\n5. Variasi: naik 2 anak tangga sekaligus untuk intensitas lebih\n6. Turun pelan-pelan untuk jaga lutut\n7. Ulangi 5-10 set naik-turun",
                'manfaat' => 'Membakar 2-3x lebih banyak kalori dari jalan biasa, memperkuat paha dan glutes, meningkatkan daya tahan, bisa dilakukan di mana saja.',
                'otot_target' => 'Paha, betis, glutes, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '5-10 set naik-turun',
                'level' => 'menengah',
                'peralatan' => 'tangga',
            ],
            'Push Up' => [
                'instruksi' => "1. Posisi plank: tangan selebar bahu, badan lurus\n2. Turunkan dada sampai hampir menyentuh lantai\n3. Siku ditekuk 45 derajat dari badan (bukan 90)\n4. Dorong kembali ke atas sampai lengan lurus\n5. Jaga core kencang, jangan angkat pinggul\n6. Bernapas: hirup saat turun, buang saat dorong\n7. Pemula: mulai dari lutut (knee push up)",
                'manfaat' => 'Memperkuat dada, bahu, trisep, dan core. Bisa dilakukan di mana saja tanpa alat. Meningkatkan kekuatan fungsional tubuh atas.',
                'otot_target' => 'Dada, bahu, trisep, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '3 set x 10-15 rep',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Sit Up' => [
                'instruksi' => "1. Berbaring, lutut ditekuk, kaki rata di lantai\n2. Tangan di belakang kepala atau silang di dada\n3. Angkat badan ke atas sampai dada mendekati lutut\n4. Turun pelan-pelan, jangan jatuh\n5. Jangan tarik leher dengan tangan\n6. Fokus kontraksi otot perut\n7. Variasi: crunch (angkat bahu saja) lebih aman untuk punggung",
                'manfaat' => 'Memperkuat otot perut (rectus abdominis), meningkatkan stabilitas core, membantu postur tubuh.',
                'otot_target' => 'Perut, hip flexor',
                'durasi_rekomendasi' => 10,
                'set_rep' => '3 set x 15-20 rep',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Plank' => [
                'instruksi' => "1. Posisi push up, tapi bertumpu pada siku\n2. Siku tepat di bawah bahu\n3. Badan lurus dari kepala sampai tumit\n4. Kencangkan perut, jangan biarkan pinggul turun\n5. Pandangan ke lantai, leher netral\n6. Bernapas normal, jangan menahan napas\n7. Mulai 20 detik, tingkatkan ke 60 detik\n8. Variasi: side plank, plank dengan angkat kaki",
                'manfaat' => 'Memperkuat seluruh core (perut, punggung bawah, obliques), meningkatkan stabilitas, memperbaiki postur, mencegah sakit punggung.',
                'otot_target' => 'Core, perut, punggung bawah, bahu',
                'durasi_rekomendasi' => 10,
                'set_rep' => '3 set x 30-60 detik',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Squat' => [
                'instruksi' => "1. Berdiri, kaki selebar bahu, jari kaki sedikit keluar\n2. Turunkan badan seperti mau duduk di kursi\n3. Lutut mengikuti arah jari kaki, jangan melewati jari kaki\n4. Turun sampai paha sejajar lantai (atau sejauh yang nyaman)\n5. Punggung tetap lurus, dada tegak\n6. Dorong tumit untuk berdiri kembali\n7. Kencangkan glutes di posisi atas\n8. Variasi: sumo squat, jump squat, goblet squat",
                'manfaat' => 'Memperkuat paha, glutes, dan core. Gerakan fungsional terpenting. Meningkatkan metabolisme karena melatih otot besar.',
                'otot_target' => 'Paha, glutes, hamstring, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '3 set x 15-20 rep',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Angkat Beban' => [
                'instruksi' => "1. Pilih beban yang bisa diangkat 8-12 rep dengan form benar\n2. Pemanasan: 1 set ringan 15 rep\n3. Gerakan dasar: bench press, shoulder press, bicep curl, row\n4. Angkat dengan kontrol, jangan menghentak\n5. Turunkan pelan (2-3 detik)\n6. Bernapas: buang saat angkat, hirup saat turun\n7. Istirahat 60-90 detik antar set\n8. Tingkatkan beban bertahap setiap minggu",
                'manfaat' => 'Membangun massa otot, meningkatkan metabolisme basal, memperkuat tulang, mencegah osteoporosis, membentuk tubuh.',
                'otot_target' => 'Tergantung gerakan (dada, punggung, bahu, lengan, kaki)',
                'durasi_rekomendasi' => 40,
                'set_rep' => '3-4 set x 8-12 rep per gerakan',
                'level' => 'menengah',
                'peralatan' => 'dumbbell_barbell',
            ],
            'Pull Up' => [
                'instruksi' => "1. Pegang bar dengan grip overhand selebar bahu\n2. Gantung dengan lengan lurus, kaki tidak menyentuh lantai\n3. Tarik badan ke atas sampai dagu melewati bar\n4. Turun pelan-pelan sampai lengan lurus\n5. Jaga core kencang, jangan berayun\n6. Pemula: gunakan resistance band untuk bantuan\n7. Atau mulai dengan negative pull up (turun pelan dari atas)",
                'manfaat' => 'Memperkuat punggung, bisep, dan grip. Salah satu latihan bodyweight terbaik untuk tubuh atas. Meningkatkan kekuatan fungsional.',
                'otot_target' => 'Punggung (lats), bisep, bahu, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '3 set x 5-10 rep',
                'level' => 'lanjutan',
                'peralatan' => 'pull_up_bar',
            ],
            'Lunges' => [
                'instruksi' => "1. Berdiri tegak, kaki rapat\n2. Langkah satu kaki ke depan, turunkan badan\n3. Kedua lutut ditekuk 90 derajat\n4. Lutut belakang hampir menyentuh lantai\n5. Lutut depan tidak melewati jari kaki\n6. Dorong kaki depan untuk kembali berdiri\n7. Ganti kaki, ulangi\n8. Variasi: walking lunges, reverse lunges, side lunges",
                'manfaat' => 'Memperkuat paha dan glutes secara unilateral (satu sisi), meningkatkan keseimbangan, memperbaiki asimetri otot.',
                'otot_target' => 'Paha, glutes, hamstring, core',
                'durasi_rekomendasi' => 15,
                'set_rep' => '3 set x 12 rep per kaki',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Yoga' => [
                'instruksi' => "1. Mulai dengan Mountain Pose: berdiri tegak, bernapas dalam\n2. Sun Salutation: rangkaian gerakan pemanasan\n3. Warrior I & II: perkuat kaki dan buka pinggul\n4. Downward Dog: peregangan punggung dan hamstring\n5. Tree Pose: latih keseimbangan\n6. Child's Pose: istirahat dan relaksasi\n7. Savasana: berbaring rileks 5 menit di akhir\n8. Fokus pada napas: hirup 4 detik, tahan 4, buang 4",
                'manfaat' => 'Meningkatkan fleksibilitas, mengurangi stres dan kecemasan, memperbaiki postur, meningkatkan keseimbangan, membantu tidur lebih baik.',
                'otot_target' => 'Seluruh tubuh, fokus fleksibilitas',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-60 menit',
                'level' => 'pemula',
                'peralatan' => 'matras_yoga',
            ],
            'Stretching' => [
                'instruksi' => "1. Hamstring stretch: duduk, raih jari kaki, tahan 20 detik\n2. Quad stretch: berdiri, tarik kaki ke belakang, tahan 20 detik\n3. Shoulder stretch: tarik lengan menyilang dada, tahan 20 detik\n4. Chest stretch: tangan di belakang, buka dada, tahan 20 detik\n5. Hip flexor stretch: posisi lunge, dorong pinggul ke depan\n6. Cat-cow: merangkak, lengkungkan dan bulatkan punggung\n7. Neck stretch: miringkan kepala ke samping, tahan 15 detik\n8. Jangan bouncing! Tahan posisi dengan stabil",
                'manfaat' => 'Meningkatkan fleksibilitas, mencegah cedera, mengurangi kaku otot, memperbaiki sirkulasi darah, membantu recovery setelah olahraga.',
                'otot_target' => 'Seluruh tubuh',
                'durasi_rekomendasi' => 15,
                'set_rep' => '10-15 menit, tahan 20-30 detik per posisi',
                'level' => 'pemula',
                'peralatan' => 'tanpa_alat',
            ],
            'Pilates' => [
                'instruksi' => "1. The Hundred: berbaring, angkat kaki 45°, pompa lengan 100x\n2. Roll Up: berbaring, gulung badan ke atas pelan-pelan\n3. Single Leg Circle: angkat kaki, buat lingkaran kecil\n4. Criss Cross: bicycle crunch dengan kontrol\n5. Swimming: tengkurap, angkat lengan-kaki bergantian\n6. Teaser: V-sit, tahan keseimbangan\n7. Fokus pada kontrol gerakan dan napas\n8. Kualitas > kuantitas",
                'manfaat' => 'Memperkuat core dalam (deep stabilizer), memperbaiki postur, meningkatkan fleksibilitas, rehabilitasi cedera, membentuk otot lean.',
                'otot_target' => 'Core, punggung, pinggul, paha',
                'durasi_rekomendasi' => 30,
                'set_rep' => '30-45 menit',
                'level' => 'pemula',
                'peralatan' => 'matras_yoga',
            ],
            'HIIT Workout' => [
                'instruksi' => "1. Pemanasan 3 menit: jumping jack + high knees\n2. Siklus 20 detik kerja, 10 detik istirahat:\n   - Burpees\n   - Mountain climbers\n   - Jump squat\n   - Push up\n   - High knees\n3. Ulangi siklus 4-6 kali\n4. Istirahat 1 menit antar siklus\n5. Pendinginan 3 menit stretching\n6. Total waktu: 15-25 menit",
                'manfaat' => 'Membakar kalori sangat tinggi dalam waktu singkat, meningkatkan metabolisme hingga 24 jam setelah latihan (afterburn effect), meningkatkan VO2max.',
                'otot_target' => 'Seluruh tubuh',
                'durasi_rekomendasi' => 20,
                'set_rep' => '4-6 siklus x 5 gerakan',
                'level' => 'menengah',
                'peralatan' => 'tanpa_alat',
            ],
            'Burpees' => [
                'instruksi' => "1. Berdiri tegak\n2. Jongkok, letakkan tangan di lantai\n3. Lompat kaki ke belakang (posisi plank)\n4. Lakukan 1 push up\n5. Lompat kaki kembali ke jongkok\n6. Lompat ke atas dengan tangan di atas kepala\n7. Mendarat dengan lutut sedikit ditekuk\n8. Pemula: skip push up dan lompatan",
                'manfaat' => 'Full-body exercise terbaik, membakar kalori sangat tinggi, melatih kekuatan + kardio sekaligus, meningkatkan explosive power.',
                'otot_target' => 'Seluruh tubuh: dada, lengan, core, kaki',
                'durasi_rekomendasi' => 10,
                'set_rep' => '3 set x 8-12 rep',
                'level' => 'menengah',
                'peralatan' => 'tanpa_alat',
            ],
            'Mountain Climbers' => [
                'instruksi' => "1. Posisi plank: tangan di bawah bahu, badan lurus\n2. Tarik lutut kanan ke dada\n3. Kembalikan, ganti lutut kiri ke dada\n4. Lakukan bergantian dengan cepat seperti berlari\n5. Jaga pinggul tetap rendah, jangan naik\n6. Core tetap kencang sepanjang gerakan\n7. Bernapas teratur\n8. Pemula: lakukan pelan-pelan dulu",
                'manfaat' => 'Melatih kardio + core sekaligus, membakar kalori tinggi, meningkatkan kelincahan, memperkuat bahu dan lengan.',
                'otot_target' => 'Core, bahu, paha, hip flexor',
                'durasi_rekomendasi' => 10,
                'set_rep' => '3 set x 30-45 detik',
                'level' => 'menengah',
                'peralatan' => 'tanpa_alat',
            ],
            'Tabata' => [
                'instruksi' => "1. Pilih 1 gerakan (squat, push up, burpee, dll)\n2. Lakukan 20 detik ALL-OUT (secepat mungkin)\n3. Istirahat 10 detik\n4. Ulangi 8 kali (total 4 menit per gerakan)\n5. Istirahat 1 menit\n6. Ganti gerakan, ulangi\n7. Total 4-5 gerakan = 20-25 menit\n8. Ini SANGAT intens - pastikan sudah pemanasan!",
                'manfaat' => 'Protokol HIIT paling efisien, membakar lemak maksimal dalam waktu minimal, meningkatkan kapasitas aerobik dan anaerobik sekaligus.',
                'otot_target' => 'Seluruh tubuh',
                'durasi_rekomendasi' => 20,
                'set_rep' => '8 set x 20 detik per gerakan',
                'level' => 'lanjutan',
                'peralatan' => 'tanpa_alat',
            ],
        ];

        foreach ($guides as $nama => $data) {
            ExerciseDatabase::where('nama', $nama)->update($data);
        }
    }
}
